import {  
    Box, 
    Typography, 
    Accordion,
    AccordionSummary,
    AccordionDetails,
  } from '@mui/material';
import { ExpandMore } from '@mui/icons-material';
const FAQ = () => (
    <Box mt={8}>
      <Typography variant="h4" component="h2" align="center" gutterBottom>
        Frequently Asked Questions
      </Typography>
      <Accordion sx={{ backgroundColor: '#111827', borderRadius: '10px' }}>
        <AccordionSummary expandIcon={<ExpandMore />}>
          <Typography>How does the AI generate flashcards?</Typography>
        </AccordionSummary>
        <AccordionDetails>
          <Typography>
            Our AI analyzes your input text or documents, identifies key concepts, and creates question-answer pairs that form the basis of your flashcards. It uses natural language processing to ensure the questions are relevant and the answers are concise.
          </Typography>
        </AccordionDetails>
      </Accordion>
      <Accordion sx={{ backgroundColor: '#111827', borderRadius: '10px' }}>
        <AccordionSummary expandIcon={<ExpandMore />}>
          <Typography>Can I edit the AI-generated flashcards?</Typography>
        </AccordionSummary>
        <AccordionDetails>
          <Typography>
            Yes, you can edit any flashcard generated by the AI. We encourage users to review and customize their flashcards to ensure they align perfectly with their learning goals.
          </Typography>
        </AccordionDetails>
      </Accordion>
      <Accordion sx={{ backgroundColor: '#111827', borderRadius: '10px' }}>
        <AccordionSummary expandIcon={<ExpandMore />}>
          <Typography>What file formats can I use for input?</Typography>
        </AccordionSummary>
        <AccordionDetails>
          <Typography>
            Our Basic plan supports plain text input. The Pro and Team plans support only PDF and plain text input.
          </Typography>
        </AccordionDetails>
      </Accordion>
    </Box>
);

export default FAQ;
